export const VERIFY_TOKEN_STARTED = 'VERIFY_TOKEN_STARTED';
export const VERIFY_TOKEN_END = 'VERIFY_TOKEN_END';

export const USER_LOGIN_STARTED = 'USER_LOGIN_STARTED';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_SIGNUP_STARTED = 'USER_SIGNUP_STARTED';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';

export const USER_GET_STARTED = 'USER_GET_FAILURE';
export const USER_GET_FAILURE = 'USER_GET_FAILURE';

export const PROFILE_UPDATE_STARTED = 'PROFILE_UPDATE_STARTED';
export const PROFILE_UPDATE_FAILURE = 'PROFILE_UPDATE_FAILURE';
export const VERIFY_PROFILE_UPDATE_SUCCESS = 'VERIFY_PROFILE_UPDATE_SUCCESS';

export const VERIFY_USER_SUCCESS = 'VERIFY_USER_SUCCESS';
export const VERIFY_GET_USER_SUCCESS = 'VERIFY_GET_USER_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const VERIFY_SIGNUP_SUCCESS = 'VERIFY_SIGNUP_SUCCESS';